### ISSUE TITLE
New button set

### ISSUE THREAD

**Issue by Ksengine** [KsTGTeam/Beautify#5]
create new beautiful button.

**Comment by Ksengine** [comment]
what about
```css
.btn,
.button{
  border: none;
  color: white;
  padding: 8px 16px;
  font-size: 16px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}
```
